[package]
name = "tui"
version = "0.0.1"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "Cursive Interface"
edition = "2018"

[dependencies]
utils = { path = "../utils" }

[dependencies.cursive]
version = "0.13"
default-features = false
features = ["termion-backend"]
